sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 4, and there are 41 supplied. Need to give the appropiate list to the executemany